login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  password:

connection: &connection
  encoding: unicode
  pool: 5


development:
  username: werkd_dev
  database: werkd_dev
  <<: *login
  <<: *connection

test:
  username: werkd_test
  database: werkd_test
  <<: *login
  <<: *connection
