# Google: https://code.google.com/apis/console
# Yahoo: http://developer.apps.yahoo.com/projects/
# Hotmail: https://manage.dev.live.com/Applications/Index
development:
 google:
  client: 167144929226-43tdrbru81nhctrqjrps2leq5nu6s3ht.apps.googleusercontent.com
  secret: -7BF5WIdnB8aLadPDgZcwK9O
 yahoo:
  consumer: "dj0yJmk9VHQwRWxaT2xIeHE3JmQ9WVdrOWVHZDZhVGxRTm04bWNHbzlNVGN5TmpJek9UVTJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD1kYQ--"
  secret: 489ca4a128616c8307cd74effad38ade6aedb370
 hotmail:
  client: 000000004C0F6A14
  secret: Aivh7wdGo3Maf66Fsa4jrpgvbKVJ5Umw

test:
 google:
  client: no_client
  secret: no_secret
 yahoo:
  consumer: no_consumer
  secret: no_secret
 hotmail:
  client: no_client
  secret: no_secret

production:
 google:
  client: 167144929226-6rii4jghfgnl7uqokjosssbiop9prbnh.apps.googleusercontent.com
  secret: pkB3WlcnZC2kMKKYBzaxnc9B
 yahoo:
  consumer: dj0yJmk9ZXg3Z0pOc0hBMGFQJmQ9WVdrOWVIcFBZa2hoTXpnbWNHbzlNVEF3T0RnNE1UWXkmcz1jb25zdW1lcnNlY3JldCZ4PTAy
  secret: b4e8f08107038e844e718b34b8a699cbff140dcf
 hotmail:
  client: 000000004C0F6A13
  secret: GyOEoRFH3Wljsn0L9UeYkCljb4LZXuuG
